language: python
python:
- '2.6'
install: true
script:
- sh buildscripts/run_tests.sh
after_success:
- sh buildscripts/generate_documentation.sh
- sh buildscripts/publish_developer_branch.sh
branches:
  only:
  - development
env:
  global:
  #usr,pw,gh_token, s3_id&key, gs_id&key, webdav_usr&pwd
  - secure: KlCTerTwn7SZnW8z7wcv0NW2LbVt63HqPddnt6NJEqI0G2VzZbk3HNeWehcll3yPkavE2rQfa58TIN4Tkn03lbDWeTqtPdHD+VR3xkrGhrC672n9YEoM1rgaY5dAmhqbuSXB6EjNwXr/Ry91HtFwC+m0gcvZ1lnnDLoaosV6SYU=
  - secure: cyBcqoKCisTGGsgPp1F04VYdJTu7d3U5ma4ieP2yfFwIlKLSNg2qtZNf7tMAHYm4cz+dpnksVd54LWjA7XHODmMrBRhp4RwhKDo8835hx2q/KAKCkLD79gXwUVE42QqfyLEYAxBpRe3+ASKtJRDOhdVF6f/hK6XSSo5YcEaWQ4w=
  - secure: SQQVDBOVZ1Slwnj1yaEh6gpIM+Pdi03b81k+fl+AWwhmVDB1lTXBb3PPI+V8lvLSN3eia9xUIaVOF5B+/wOWbxwR17plD1mD/sVaZn/GkSJtiKLTr+h7goVcFff2toahtuPYg8IhLnaWgUpB7Xqvr739peloCKBRT1HmNuNf2mg=
  - secure: PnTYKAuSTgpUlkYE2oLEcrD0kVvtL92MRRJTTHdfyOayIaU1NLxr8FpP1R8jx/fW9XQKoV1ixL1YPR+ir7YMNGyFgv9Vnlk8TC3SiM0flO7Ui1z1GBHUUEfuBCHJCJc/ejzt+nDk4aI1gaZJi8dz9yxgrrbOsUdbB/MDBDXz0/k=
  - secure: MAMBzpC5bsKR2Em1dG/bBOEXwFyYzxDm3/f8rNlS5e235DVLj6/UstwE3yHhb7g1DXo53IZ57VsYxqrHKucGxxJITYc9p1g1HX/3MR+BQ24dWzMuvBdLEqamXTrRzKze1BQ2Ns2zpIW4o3Q8oN3Z7vGZjYM/r3fCBXpKpQl/irM=
  - secure: WvzuGWXJcT/gl6CEu2lHaqMCdtZOmjKBs3CWl7hTT9erScXNv7RH3VYA80HsAACdyZkY80gwtrxnmDX4GpMMUkAqUr3IIkkN55kaj1eTjt1sNVZu0Xw/a5dCX3UcD9pYmQ6C21S0WMCxCuJFm53xRtSafcRC6yaQqJ7PLiY98lM=
  - secure: A7bQsL60X2w0EZoO8tFdS0eOaruL6hXGfNOF93wR0fwV5PvktQFir8UvvDrb3tTmxacUolnHITWOquU1XsRZ0aUmrJ+YDLmfW9dLLmDGXekH9os9E8w04EJMmyqAE66U/T831r88SU3fNGwPKp74R63T+oMKLa0VNH/ddw2MhDk=
  - secure: SjR+uaKxpb+TEAY+2VYZPSEbleA9jR5Ok93BIO8gzHQ9V8cFX6tl/7EBDtT6c1JCDCBq8oNVKnwX9gWdqCItiyX7GxSoPI2tsN0Ed3oz2bbQp2NhHjkK00bPgudda+hPQVyC2EHJDmlmydYTa7r8u3oXUqRMboEmZH9HRLNZrQ8=
  - secure: act/B9GPpEfBj3YUmsO7h29HjbYrkCb7IBavYxIur0y0/PVi35F3TjmQjLsOsDRXPhRN5YRWDUy1xM+AMISy6rbYCVHC1Y0lS3whERCoKNCjgoCEbwHGxdw84q9Itr0VDYt09J0IlJHdprS+vN4w4DBoQ4dEC/hvC4o8TZXd+Ac=
  - secure: BliJZU3YuPGcDHeiOiQZ+neDjbSCDL29Wk/E1USJFtCLb1gTCjX69fGnjGBRdcYGv/rLZEz4Y9fSAI0hBFAolysn37Fiwic/9bu21kHGuH0NlUhbzkUcfdBP/DvXVTlaxNnH0TeljCGcgsB4jeLd+tCZZ/wBapTOqM9YdnNtBXs=
cache: apt
